-- Database Exploration.
-- Explore all oblects in the Dataase
SELECT 
    *
FROM
    information_schema.tables;
-- Explore all columns in database
SELECT 
    *
FROM
    information_schema.columns;
    
-- Dimensions Explorations.
-- explore all countries our customers came from.
SELECT DISTINCT
    country
FROM
    dim_customers;
-- explore major categories "the major Divisions.
SELECT DISTINCT
    category, subcategory, product_name
FROM
    dim_products
ORDER BY 1 , 2 , 3;
SELECT 
    COUNT(product_name)
FROM
    dim_products;
-----------------------------------------------------------------------------------------------------------------
-- Date Exploration.
-- find the date of first and last order.
-- how many years of sales are avaiable.alter.
SELECT 
    MIN(order_date) AS first_order,
    MAX(order_date) AS last_order,
    TIMESTAMPDIFF(YEAR,
        MIN(order_date),
        MAX(order_date)) AS order_range_month
FROM
    fact_sales
WHERE
    order_date IS NOT NULL
        AND CAST(order_date AS CHAR) != '0000-00-00';

-- find the youngest and oldest customer.
SELECT 
    MIN(birthdate) AS youngest,
    TIMESTAMPDIFF(YEAR,
        MIN(birthdate),
        CURDATE()) AS oldest_age,
    TIMESTAMPDIFF(YEAR,
        MAX(birthdate),
        CURDATE()) AS youngest_age,
    MAX(birthdate) AS oldest
FROM
    dim_customers
WHERE
    birthdate IS NOT NULL
        AND CAST(birthdate AS CHAR) != '0000-00-00';
---------------------------------------------------------------------------------------------
-- 4.Measure Exploration.
-- Find the totalsales.
SELECT 
    SUM(sales_amount) AS total_sales
FROM
    fact_sales;
-- Find how many items are sold.
SELECT 
    SUM(quantity) AS total_quantity
FROM
    fact_sales;
-- Find the average selling price
SELECT 
    ROUND(AVG(price), 0) AS avg_price
FROM
    fact_sales;
-- Find the Total number of Orders
SELECT 
    COUNT(DISTINCT order_number) AS total_orders
FROM
    fact_sales;
-- Find the total number of products
SELECT 
    COUNT(DISTINCT product_name) AS total_product
FROM
    dim_products;
-- Find the total number of customers
SELECT 
    COUNT(DISTINCT customer_key) AS total_customers
FROM
    fact_sales;
-- Find the total number of customers that has placed an order
select count(distinct customer_key) order_placed from fact_sales;
-- Generate a Report that shows all key metrics of the business.
SELECT 
    'total sales' AS measure_name,
    ROUND(SUM(sales_amount), 0) AS measure_value
FROM
    fact_sales 
UNION ALL SELECT 
    'total quantity', ROUND(SUM(quantity), 0)
FROM
    fact_sales 
UNION ALL SELECT 
    'average price', ROUND(AVG(price), 0)
FROM
    fact_sales 
UNION ALL SELECT 
    'total nr. orders', ROUND(COUNT(DISTINCT order_number), 0)
FROM
    fact_sales 
UNION ALL SELECT 
    'total nr. products', ROUND(COUNT(product_name), 0)
FROM
    dim_products 
UNION ALL SELECT 
    'total nr. customers', ROUND(COUNT(customer_key), 0)
FROM
    dim_customers;
---------------------------------------------------------------------------------------------
-- 5.Magnitude Analysis.
-- Find total customers by countries.
select country,count( distinct customer_key) as total_customers from dim_customers
group by country;

-- Find total customers by gender
select gender,count(distinct customer_number) as total_customers from dim_customers
group by gender;

-- Find total products by category.
select category,count(product_key) as total_products from dim_products
group by  category;

-- What is the average costs in each category?
select category,round(avg(cost),2) as avg_cost from dim_products
group by category;

-- What is the total revenue generated for each category?
select p.category,
sum(f.sales_amount) as total_revenue
from dim_products p
left join fact_sales f
on p.product_key = f.product_key
group by 1
having total_revenue is not null
order by 2 desc;

-- Find total revenue is generated by each customer.
select customer_key as customers,sum(sales_amount) as total_revenue from fact_sales
group by 1
order by 2 desc;

-- What is the distribution of sold items across countries?;
SELECT 
    c.country,
    SUM(f.quantity) AS total_quantity
FROM fact_sales f
LEFT JOIN dim_customers c ON f.customer_key = c.customer_key
GROUP BY 1
ORDER BY 2 DESC;
--------------------------------------------------------------------------------------------------------------
-- Rank Analysis.
-- Which 5 products generate the highest evenue?
select *
from(
select p.product_name,
sum(f.sales_amount) as total_revenue,
row_number() over(order by sum(f.sales_amount) desc) as rank_products
from dim_products p
left join fact_sales f
on p.product_key = f.product_key
group by 1
having total_revenue is not null
order by 2 desc) t
where rank_products <=5;


-- Which 5 products generate the worst evenue?
select p.product_name,
sum(f.sales_amount) as total_revenue,
row_number() over(order by sum(f.sales_amount)) as rank_products
from dim_products p
left join fact_sales f
on p.product_key = f.product_key
group by 1
having total_revenue is not null
order by 2 asc
limit 5;

-- The 3 customers with the fewest orders placed
SELECT  
    f.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT order_number) AS total_orders
FROM fact_sales f
LEFT JOIN dim_customers c ON c.customer_key = f.customer_key
GROUP BY f.customer_key, c.first_name, c.last_name
ORDER BY total_orders asc
limit 3;
